"""Initial migration - create tables

Revision ID: f1b842f03222
Revises: 
Create Date: 2026-01-22 11:50:19.264661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b842f03222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencoes',
    sa.Column('resumo', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FINALIZADO', name='statusmanutencao', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_id'), 'manutencoes', ['id'], unique=False)
    op.create_table('materiais',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_nome'), 'materiais', ['nome'], unique=True)
    op.create_table('manutencao_materiais',
    sa.Column('manutencao_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manutencao_id'], ['manutencoes.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_materiais_id'), 'manutencao_materiais', ['id'], unique=False)
    op.create_index(op.f('ix_manutencao_materiais_manutencao_id'), 'manutencao_materiais', ['manutencao_id'], unique=False)
    op.create_index(op.f('ix_manutencao_materiais_material_id'), 'manutencao_materiais', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manutencao_materiais_material_id'), table_name='manutencao_materiais')
    op.drop_index(op.f('ix_manutencao_materiais_manutencao_id'), table_name='manutencao_materiais')
    op.drop_index(op.f('ix_manutencao_materiais_id'), table_name='manutencao_materiais')
    op.drop_table('manutencao_materiais')
    op.drop_index(op.f('ix_materiais_nome'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_manutencoes_id'), table_name='manutencoes')
    op.drop_table('manutencoes')
    # ### end Alembic commands ###
